config/routes.rb
Authenticate::Application.routes.draw do

  get 'register', to: 'users#new', as: 'register'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :password_resets

  get "welcome/index"

   root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :name, :password, :password_confirmation, :auth_token, :question
  validates_presence_of :email, :name, :password, :password_confirmation, :on => :create
  

  before_create { generate_token (:auth_token)}
  #runs generate_token method, passing it into auth_token column

  def send_password_reset
    generate_token(:password_reset_token)
    save!
    #generates token, saves into password_reset_token column, saves in place
    UserMailer.password_reset(self).deliver
    # invokes the UserMailer, uses the password_reset on the user, deliver sends the actual message
  end

  # any db column can later be given as an argument
  def generate_token(column)
  	begin
  #creates a token string, which will be added to column
  	  self[column] = SecureRandom.urlsafe_base64
  #creates a loop, adding to column only if the SecureRandom generated token
  #matches no other token. Ensures unique token string.
  	end while User.exists?(column => self[column])
  
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private
  def current_user
  # @current_user will only be valid if there is an auth token
  	@current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
  # helper_method allows instance variable @current_user to be accessed from the view
  helper_method :current_user
  def authorize
    redirect_to login_url if current_user.nil?
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def index

  end

  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	user.send_password_reset if user
  	redirect_to root_url

  end

  def edit
  	@user = User.find_by_password_reset_token!(params[:id])
  	#routes to the correct edit page, using the token passed into the url from the email
  end

  def update
  	#standard rails CRUD method
  	@user = User.find_by_password_reset_token!(params[:id])
  	if @user.update_attributes(params[:user])

  	redirect_to root_url, :notice => "Password Updated!"
  	end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	# creates a session by comparing finding a user entered in login form, and 
	# checking whether the authenticate method passes back as "true"
	def create
	user = User.find_by_email(params[:email])
		if user && user.authenticate
			session[:user_id] = user.id
			redirect_to root_url
		else
			render 'new'
		end
	end
	# by setting the user_id to nil, halts any controller reliant on the session
	def destroy
		session[:user_id] = nil
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	# creates a session by comparing finding a user entered in login form, and 
	# checking whether the authenticate method passes back as "true"
	def create
	user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			cookies.permanent[:auth_token] = user.auth_token
			redirect_to root_url
		else
			render 'new'
		end
	end
	# by setting the user_id to nil, halts any controller reliant on the session
	def destroy
		cookies.delete(:auth_token)
		redirect_to root_url
	end
	# def reset_password
	# 	user = User.find_by_email(params[:email])
	# 	if user && user.authenticate(params[:password])
	# 		session[:user_id] = user.id
	# 		redirect_to root_url
	# 	else
	# 		render 'new'
	# 	end
	# end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authenticate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Jolly+Lodger' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
</head>
<body> 
<%= link_to root_url do %>
	<h1>Frozen Plains</h1>
<% end %>


	
	
<%= yield %>

</body>
</html>

app/views/password_resets/edit.html.erb
<div class="centered winterbg">
<h1>Set a new password:</h1>
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
<!-- url is added to form tag to override default routing to users controller -->
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


   <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>
</div>

app/views/password_resets/new.html.erb
<div class="centered winterbg">
	<%= form_tag password_resets_path :method => :post do %>

	<!-- passes email to 'create' method in password_resets controller -->
		<div class="field">
			<%= label_tag :email %>
			<br />
			<%= text_field_tag :email, params[:email] %>
		</div>	
		<div class="actions"> <%= submit_tag "Send Password Reset Email" %></div>
	<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
   <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label "Security Question" %><br />
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label "Answer" %><br />
    <%= f.text_field :auth_token %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="centered winterbg">
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_path %>
</div>

app/views/users/index.html.erb
<div class="centered winterbg">
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="centered winterbg">
	<h1>New User</h1>

	<%= render 'form' %>

	<%= link_to 'Back', root_path %>

</div>

app/views/users/show.html.erb
<div class="centered winterbg">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_path %>
</div>

app/views/welcome/index.html.erb
<div class="centered winterbg">
<% if current_user %>
	Welcome, <%= current_user.name %>!
	<h1>Coming Soon!</h1>
	<%= link_to "Log Out", logout_path %>
<% else %>
	<h1>Hello!</h1>
	<!-- each path points to the aliased route in routes.rb -->
	<p><%= link_to "Log In", login_path %> or <%= link_to "Register", register_path %> to continue.</p>

<% end %>
</div>